language: python
jobs:
  include:
    - name: "Python 3.8.6 on macOS"
      os: osx
      osx_image: xcode11.2  # Python 3.7.4 running on macOS 10.14.4
      language: shell  
install:
        - pipenv install
script: "python3 test.py""
